/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as WorkspaceRouteImport } from "./routes/workspace";
import { Route as WorkspaceIndexRouteImport } from "./routes/workspace.index";
import { Route as WorkspaceArtifactsArtifactIdRouteImport } from "./routes/workspace.artifacts.$artifactId";
import { Route as WorkspaceNotesNoteIdRouteImport } from "./routes/workspace.notes.$noteId";
import { Route as WorkspaceProjectsProjectIdRouteImport } from "./routes/workspace.projects.$projectId";
import { Route as WorkspaceThreadsThreadIdRouteImport } from "./routes/workspace.threads.$threadId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: "/workspace",
  path: "/workspace",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceArtifactsArtifactIdRoute =
  WorkspaceArtifactsArtifactIdRouteImport.update({
    id: "/artifacts/$artifactId",
    path: "/artifacts/$artifactId",
    getParentRoute: () => WorkspaceRoute,
  } as any);
const WorkspaceNotesNoteIdRoute = WorkspaceNotesNoteIdRouteImport.update({
  id: "/notes/$noteId",
  path: "/notes/$noteId",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: "/projects/$projectId",
    path: "/projects/$projectId",
    getParentRoute: () => WorkspaceRoute,
  } as any);
const WorkspaceThreadsThreadIdRoute =
  WorkspaceThreadsThreadIdRouteImport.update({
    id: "/threads/$threadId",
    path: "/threads/$threadId",
    getParentRoute: () => WorkspaceRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRoute;
  "/workspace": typeof WorkspaceRouteWithChildren;
  "/workspace/": typeof WorkspaceIndexRoute;
  "/workspace/artifacts/$artifactId": typeof WorkspaceArtifactsArtifactIdRoute;
  "/workspace/notes/$noteId": typeof WorkspaceNotesNoteIdRoute;
  "/workspace/projects/$projectId": typeof WorkspaceProjectsProjectIdRoute;
  "/workspace/threads/$threadId": typeof WorkspaceThreadsThreadIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthRoute;
  "/workspace": typeof WorkspaceIndexRoute;
  "/workspace/artifacts/$artifactId": typeof WorkspaceArtifactsArtifactIdRoute;
  "/workspace/notes/$noteId": typeof WorkspaceNotesNoteIdRoute;
  "/workspace/projects/$projectId": typeof WorkspaceProjectsProjectIdRoute;
  "/workspace/threads/$threadId": typeof WorkspaceThreadsThreadIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/auth": typeof AuthRoute;
  "/workspace": typeof WorkspaceRouteWithChildren;
  "/workspace/": typeof WorkspaceIndexRoute;
  "/workspace/artifacts/$artifactId": typeof WorkspaceArtifactsArtifactIdRoute;
  "/workspace/notes/$noteId": typeof WorkspaceNotesNoteIdRoute;
  "/workspace/projects/$projectId": typeof WorkspaceProjectsProjectIdRoute;
  "/workspace/threads/$threadId": typeof WorkspaceThreadsThreadIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/workspace"
    | "/workspace/"
    | "/workspace/artifacts/$artifactId"
    | "/workspace/notes/$noteId"
    | "/workspace/projects/$projectId"
    | "/workspace/threads/$threadId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/workspace"
    | "/workspace/artifacts/$artifactId"
    | "/workspace/notes/$noteId"
    | "/workspace/projects/$projectId"
    | "/workspace/threads/$threadId";
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/workspace"
    | "/workspace/"
    | "/workspace/artifacts/$artifactId"
    | "/workspace/notes/$noteId"
    | "/workspace/projects/$projectId"
    | "/workspace/threads/$threadId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRoute;
  WorkspaceRoute: typeof WorkspaceRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workspace": {
      id: "/workspace";
      path: "/workspace";
      fullPath: "/workspace";
      preLoaderRoute: typeof WorkspaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workspace/": {
      id: "/workspace/";
      path: "/";
      fullPath: "/workspace/";
      preLoaderRoute: typeof WorkspaceIndexRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/workspace/artifacts/$artifactId": {
      id: "/workspace/artifacts/$artifactId";
      path: "/artifacts/$artifactId";
      fullPath: "/workspace/artifacts/$artifactId";
      preLoaderRoute: typeof WorkspaceArtifactsArtifactIdRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/workspace/notes/$noteId": {
      id: "/workspace/notes/$noteId";
      path: "/notes/$noteId";
      fullPath: "/workspace/notes/$noteId";
      preLoaderRoute: typeof WorkspaceNotesNoteIdRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/workspace/projects/$projectId": {
      id: "/workspace/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/workspace/projects/$projectId";
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/workspace/threads/$threadId": {
      id: "/workspace/threads/$threadId";
      path: "/threads/$threadId";
      fullPath: "/workspace/threads/$threadId";
      preLoaderRoute: typeof WorkspaceThreadsThreadIdRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
  }
}

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute;
  WorkspaceArtifactsArtifactIdRoute: typeof WorkspaceArtifactsArtifactIdRoute;
  WorkspaceNotesNoteIdRoute: typeof WorkspaceNotesNoteIdRoute;
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRoute;
  WorkspaceThreadsThreadIdRoute: typeof WorkspaceThreadsThreadIdRoute;
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceArtifactsArtifactIdRoute: WorkspaceArtifactsArtifactIdRoute,
  WorkspaceNotesNoteIdRoute: WorkspaceNotesNoteIdRoute,
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRoute,
  WorkspaceThreadsThreadIdRoute: WorkspaceThreadsThreadIdRoute,
};

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
