import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  attentionItem: {
    borderTopColor: "#3f3f46",
    borderTopWidth: 1,
    marginTop: 12,
    paddingTop: 4,
  },
  body: { color: "#e4e4e7", fontSize: 16, lineHeight: 24 },
  button: {
    backgroundColor: "#27272a",
    borderRadius: 12,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  buttonText: { color: "#fafafa", fontSize: 15, fontWeight: "700" },
  buttonDisabled: { opacity: 0.55 },
  connectionRow: {
    alignItems: "stretch",
    borderColor: "#3f3f46",
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    marginTop: 16,
    padding: 18,
  },
  connectionStatus: { color: "#d4d4d8", fontSize: 13, fontWeight: "700" },
  detailTitle: {
    color: "#fafafa",
    fontSize: 34,
    fontWeight: "700",
    letterSpacing: -1.2,
    marginBottom: 20,
    marginTop: 8,
  },
  error: { color: "#ffaaa3", fontSize: 14, lineHeight: 21, marginTop: 8 },
  executionOutput: {
    backgroundColor: "#18181b",
    borderColor: "#3f3f46",
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    maxHeight: 280,
    padding: 12,
  },
  eyebrow: { color: "#a1a1aa", fontSize: 12, fontWeight: "700", letterSpacing: 2 },
  input: {
    backgroundColor: "#18181b",
    borderColor: "#52525b",
    borderRadius: 12,
    borderWidth: 1,
    color: "#fafafa",
    fontSize: 15,
    marginTop: 14,
    padding: 14,
  },
  label: { color: "#fafafa", fontSize: 15, fontWeight: "700" },
  listCard: { backgroundColor: "#27272a", borderRadius: 14, marginTop: 10, padding: 16 },
  listTitle: { color: "#fafafa", fontSize: 18, fontWeight: "700", marginBottom: 4 },
  muted: { color: "#a1a1aa", fontSize: 14, lineHeight: 21, marginTop: 4 },
  navigation: { backgroundColor: "#18181b" },
  noteEditor: { flex: 1 },
  noteScreen: { backgroundColor: "#f8faf9", flex: 1 },
  noteState: { alignItems: "center", flex: 1, justifyContent: "center", padding: 24 },
  noteStatusRow: {
    alignItems: "center",
    borderBottomColor: "#dce4e0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
    paddingHorizontal: 16,
  },
  noteTitle: { color: "#18201d", flex: 1, fontSize: 17, fontWeight: "700", marginRight: 12 },
  screen: { backgroundColor: "#18181b", flexGrow: 1, padding: 24, paddingBottom: 64 },
  sectionTitle: { color: "#fafafa", fontSize: 20, fontWeight: "700", marginTop: 24 },
  stateCard: {
    backgroundColor: "#27272a",
    borderColor: "#3f3f46",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 18,
    padding: 18,
  },
  stateTitle: { color: "#fafafa", fontSize: 19, fontWeight: "700", marginBottom: 8 },
  summaryHeader: { marginTop: 18 },
  title: {
    color: "#fafafa",
    fontSize: 42,
    fontWeight: "700",
    letterSpacing: -1.8,
    lineHeight: 45,
    marginTop: 12,
  },
});
